# Generated by Django 4.1.3 on 2022-11-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_body_comment_comment_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='user_comment',
        ),
    ]
